version: 0.1
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
http:
  addr: :5000
notifications:
  endpoints:
    - name: listener
      url: http://regnotify:8000/api/v1/events
